### ISSUE TITLE
Input field blank unless i press '0' and i keep getting NaN on the model

### ISSUE THREAD

**Issue by HarrisRobin** [fiestah/angular-money-directive#17]
Hi,

The demo looks great, however the directive does not work and I have 0 errors. If I type any number, the input field stays blank and if i type 0 it actually populates it. Typing 0 doesn't actually update it on the model or scope however typing anything else returns NaN. Im on angular 1.2.*(latest)

Any ideas?

Cheers

**Comment by jerry4** [comment]
I'm having the same issue with latest angular (1.3.15). When I switch back to the last release (1.0.2) then everything works.

**Comment by HarrisRobin** [comment]
@jerry4  thanks for pointing that out! Didn't want to give up on this directive.

**Comment by b3by** [comment]
Apparently the parser has some issue when any number but zero in inserted in the input field. This happens because the default precision is not working properly. When not specified, the precision is undefined, and rounding any number returns NaN as output. The directive seems to work for me if I declare a default precision on the same level of the regex (outside of the link function let's say) and then before the observe I init the precision to that value.
Will try to prepare a proper pull request later today, hope this works so far.

**Comment by thatmarvin** [comment]
This should be good now — use `1.1.1` if you're still on Angular 1.2,  `1.2.0` if you're on angular 1.3 and above.

**Comment by Sevensnake** [comment]
Still a NAN problem appears using angular 1.4.5

**Comment by Sevensnake** [comment]
this is happeing in the function updateValuePrecision
 function updateValuePrecision() {
      // $modelValue shows up as NaN in 1.2 on init
      var modelValue = ngModelCtrl.$modelValue;

      if (!isNaN(modelValue) && isPrecisionValid()) {
        ngModelCtrl.$modelValue = round(modelValue);
        $parse(attrs.ngModel).assign(scope, ngModelCtrl.$modelValue);

        ngModelCtrl.$viewValue = formatPrecision(modelValue);
        ngModelCtrl.$render();
      }
    }

**Comment by Sevensnake** [comment]
ok this is happening when you click a blank textbox and leave out it add NaN

**Comment by thatmarvin** [comment]
@Sevensnake this should be fixed in v1.2.1. Please open a new issue in the future as comments in closed issues tend to get buried and unnoticed.
